version: '3'

services:
  coordinator:
    image: "bidw/presto-coordinator:${PRESTO_VERSION}"
    ports:
      - "8080:8080"
    container_name: "presto-coordinator"
    command: http://presto-coordinator:8080 presto-coordinator
  worker0:
    image: "bidw/presto-worker:${PRESTO_VERSION}"
    container_name: "presto-worker0"
    ports:
      - "8081:8081"
    command: http://presto-coordinator:8080 presto-worker0
  worker1:
    image: "bidw/presto-worker:${PRESTO_VERSION}"
    container_name: "presto-worker1"
    ports:
      - "8082:8081"
    command: http://presto-coordinator:8080 presto-worker1
